#!/bin/sh
#
# This code is released in public domain by Andrea Scarpino
# <me@andreascarpino.it>.
#
# This script is inspired by i3-sensible-terminal by i3 Han Boetes
# <han@mijncomputer.nl>.
# This one tries to exec a browser by trying some known browsers.
for browser in $BROWSER firefox chromium google-chrome-stable opera qupzilla iceweasel konqueror firefox-aurora google-chrome-beta google-chrome-dev luakit midori epiphany lynx w3m dillo elinks; do
    if command -v $browser > /dev/null 2>&1; then
        exec $browser "$@"
    fi
done

i3-nagbar -m 'i3-sensible-browser could not find a browser. Please install one.'
